export type { AuthSession, ContestMode, ContestView } from '@poker/protocol';

export { API_URL, apiBase, WS_URL } from './client';
export {
  signup,
  login,
  logout,
  refreshTicket,
  fetchMe,
  updateMe,
  requestAvatarUploadUrl,
  type MeProfile,
} from './auth';
export {
  fetchPublicProfile,
  fetchHandsTogether,
  type PublicProfile,
  type PublicProfileRelationship,
} from './users';
export {
  createTable,
  inviteTableFriends,
  listPublicTables,
  resolveInvite,
  type PublicTableSummary,
} from './tables';
export {
  listFriends,
  pingPresence,
  searchUsers,
  sendFriendRequest,
  respondFriendRequest,
  cancelFriendRequest,
  removeFriend,
  createFriendGroup,
  updateFriendGroup,
  deleteFriendGroup,
  inviteFriendGroup,
  challengeFriend,
  joinFriendChallenge,
  declineFriendChallenge,
  cancelFriendChallenge,
  type FriendProfile,
  type PendingRequest,
  type OutgoingRequest,
  type PendingChallenge,
  type OutgoingChallenge,
  type FriendGroup,
} from './friends';
export {
  createContest,
  inviteContestFriends,
  listPublicContests,
  listMyContests,
  resolveContestInvite,
  getContest,
  registerContest,
  unregisterContest,
  startContest,
} from './contests';
export {
  createLudo,
  resolveLudoInvite,
  fetchLudoChat,
  type CreateLudoResult,
  type LudoInviteResult,
  type LudoChatLine,
} from './ludo';
export {
  createSnakes,
  resolveSnakesInvite,
  fetchSnakesChat,
  type CreateSnakesResult,
  type SnakesInviteResult,
  type SnakesChatLine,
} from './snakes';
export {
  createMemory,
  resolveMemoryInvite,
  fetchMemoryChat,
  type CreateMemoryResult,
  type MemoryInviteResult,
  type MemoryChatLine,
} from './memory';
export {
  createCourtpiece,
  resolveCourtpieceInvite,
  fetchCourtpieceChat,
  type CreateCourtpieceResult,
  type CourtpieceInviteResult,
  type CourtpieceChatLine,
} from './courtpiece';
export { uploadOfflineHand, fetchMyHands, type UploadHandPayload, type MyHandRow } from './history';
export { fetchBotBanterLine } from './botBanter';
export {
  streamBotChat,
  fetchBotChatProviders,
  BOT_CHAT_LLM_PROVIDER_LABELS,
  BOT_CHAT_LLM_STORAGE_KEY,
  BOT_CHAT_STARTER_PROMPTS,
  type BotChatLlmProvider,
  type BotChatPersona,
  type BotChatTurn,
} from './botChat';
export {
  fetchPublicSite,
  fetchPublicBotGroups,
  fetchPublicBotGroupsWithLabels,
  type SiteAnnouncement,
  type SiteEconomy,
  type HomeLandingFeature,
  type HomeFeaturesByTheme,
  type PagesByTheme,
  type CopyTheme,
  type PageCopy,
  type PageCopyKey,
  type PagesCopy,
  type PublicBotGroupsResult,
  type AvatarPresetsConfig,
  DEFAULT_AVATAR_PRESET_URLS,
} from './site';
export {
  TABLE_SOUND_KINDS,
  DEFAULT_TABLE_SOUND_URLS,
  TABLE_SOUND_LABELS,
  defaultTableSoundsConfig,
  type TableSoundKind,
  type TableSoundsConfig,
} from './sounds';
export {
  fetchAdminHomeFeatures,
  patchAdminHomeFeatures,
  fetchAdminPages,
  patchAdminPages,
  fetchAdminOverview,
  fetchAdminAnnouncement,
  patchAdminAnnouncement,
  fetchAdminBotChatStarters,
  patchAdminBotChatStarters,
  MAX_BOT_CHAT_STARTERS,
  MAX_BOT_CHAT_STARTER_CHARS,
  fetchAdminEconomy,
  patchAdminEconomy,
  fetchAdminRoomSettings,
  patchAdminRoomSettings,
  fetchAdminUsers,
  creditAdminUser,
  resetAdminUserChips,
  creditAdminUserWhuffies,
  resetAdminUserWhuffies,
  deleteAdminUser,
  fetchAdminGames,
  fetchAdminBotGroups,
  patchAdminBotGroups,
  fetchAdminSounds,
  patchAdminSounds,
  fetchAdminAvatarPresets,
  patchAdminAvatarPresets,
  requestAdminSoundUploadUrl,
  requestAdminImageUploadUrl,
  fetchAdminHands,
  fetchAdminHand,
  type AdminUserRow,
  type AdminTableRow,
  type AdminContestRow,
  type AdminRoomSettings,
  type BotPersonalityId,
  type BotGroup,
  type BotGroupLabel,
  type BotGroupLabels,
  type PublicBotGroup,
  DEFAULT_BOT_GROUP_LABELS,
  type AdminHandSummary,
  type AdminHandsPage,
  type AdminHandDetail,
  type SiteImagePurpose,
} from './admin';
