export type { AuthSession, ContestMode, ContestView } from '@poker/protocol';

export { API_URL, apiBase, WS_URL } from './client';
export {
  signup,
  login,
  logout,
  refreshTicket,
  fetchMe,
  updateMe,
  requestAvatarUploadUrl,
  type MeProfile,
} from './auth';
export {
  createTable,
  inviteTableFriends,
  listPublicTables,
  resolveInvite,
  type PublicTableSummary,
} from './tables';
export {
  listFriends,
  pingPresence,
  searchUsers,
  sendFriendRequest,
  respondFriendRequest,
  removeFriend,
  createFriendGroup,
  updateFriendGroup,
  deleteFriendGroup,
  inviteFriendGroup,
  challengeFriend,
  joinFriendChallenge,
  declineFriendChallenge,
  type FriendProfile,
  type PendingRequest,
  type PendingChallenge,
  type FriendGroup,
} from './friends';
export {
  createContest,
  inviteContestFriends,
  listPublicContests,
  listMyContests,
  resolveContestInvite,
  getContest,
  registerContest,
  unregisterContest,
  startContest,
} from './contests';
export {
  createLudo,
  resolveLudoInvite,
  fetchLudoChat,
  type CreateLudoResult,
  type LudoInviteResult,
  type LudoChatLine,
} from './ludo';
export { uploadOfflineHand, fetchMyHands, type UploadHandPayload, type MyHandRow } from './history';
export {
  fetchPublicSite,
  fetchPublicBotGroups,
  type SiteAnnouncement,
  type SiteEconomy,
  type HomeLandingFeature,
  type HomeFeaturesByTheme,
  type PagesByTheme,
  type CopyTheme,
  type PageCopy,
  type PageCopyKey,
  type PagesCopy,
} from './site';
export {
  TABLE_SOUND_KINDS,
  DEFAULT_TABLE_SOUND_URLS,
  TABLE_SOUND_LABELS,
  defaultTableSoundsConfig,
  type TableSoundKind,
  type TableSoundsConfig,
} from './sounds';
export {
  fetchAdminHomeFeatures,
  patchAdminHomeFeatures,
  fetchAdminPages,
  patchAdminPages,
  fetchAdminOverview,
  fetchAdminAnnouncement,
  patchAdminAnnouncement,
  fetchAdminEconomy,
  patchAdminEconomy,
  fetchAdminRoomSettings,
  patchAdminRoomSettings,
  fetchAdminUsers,
  creditAdminUser,
  resetAdminUserChips,
  creditAdminUserWhuffies,
  resetAdminUserWhuffies,
  deleteAdminUser,
  fetchAdminGames,
  fetchAdminBotGroups,
  patchAdminBotGroups,
  fetchAdminSounds,
  patchAdminSounds,
  requestAdminSoundUploadUrl,
  requestAdminImageUploadUrl,
  fetchAdminHands,
  fetchAdminHand,
  type AdminUserRow,
  type AdminTableRow,
  type AdminContestRow,
  type AdminRoomSettings,
  type BotPersonalityId,
  type BotGroup,
  type PublicBotGroup,
  type AdminHandSummary,
  type AdminHandsPage,
  type AdminHandDetail,
  type SiteImagePurpose,
} from './admin';
